# This is a basic workflow to help you get started with Actions

name: Release

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  release:
    types: [ published ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install clang zlib1g-dev libkrb5-dev
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-build --verbosity normal
      - name: Publish
        run: dotnet publish -c Release -r linux-x64
      - name: Pack files
        run: |
          cd bin/Release/net5.0/linux-x64/publish/
          tar zcvf charplayer-linux-native-x64.tar.gz ./
          release_file_path=$(pwd)/charplayer-linux-native-x64.tar.gz
          echo release_file_path
          echo "release_file_path=$release_file_path" >> $GITHUB_ENV
          echo "pack ended."

      - name: Deploy
        uses: WebFreak001/upload-asset@v1.0.0
        with:
          file: ${{ env.release_file_path }}
          name: 'charplayer-linux-native-x64.tar.gz'
          mime: application/octet-stream
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          
